### ISSUE TITLE
A o kolik přijdou ti nejbohatější

### ISSUE THREAD

**Issue by ogicek** [isnotgood/nespravedlive-dane.cz#3]
Určitě by bylo zajímavé doplnit, jak se daňová reforma dotkne těch nejbohatších - Babiš, Kellner, Komárek apod.  Daně z dividend a podílů na zisku zůstanou 15% (a neplatí se z nich zdravotní a soc. poj.).
Sobotka lže, když tvrdí, že mu jde o zdanění nejbohatších.

**Comment by isnotgood** [comment]
Bohuzel to je asi tema, ktere nepujde vysvetlit na formatu tohoto webu jako "jednohubka". Kazdopadne kdybyste mel nejaky napad, jak to trefne podat - sem s nim :)

**Comment by ogicek** [comment]
Dobrý den,
 
nevím, jak je to složité, ale do kalkulačky např. přidat položku "Zadejte váš hrubý měsíční příjem z podílů na zisku/dividend".
 
Výsledek:
ke stávajícím hodnotám (z běžného příjmu) se přičte:
superhrubá = hrubá
zdrav. poj = 0
soc. poj = 0
sleva a bonus = to nevím, jak funguje, ale myslím, že = 0
a starý i nový příjem =  0,85 * hrubá
 
a pokud jde o ten  graf na http://slajchrt.cz/spravedlive-dane.htm
tak bych tam přidal něco  např. 3 blok -  "A teď ti nejbohatší"
 
a doplnil tam  příjmy   z podílu a dividend
např. 3 hodnoty    1 000 000, 10 mil., 100 mil.  a změna = 0
Netuším, jak snadno je to realizovatelné. 
 
Zdraví Oto Gücklhorn
 
 
______________________________________________________________
> Od: Lukas Weber <notifications@github.com>
> Komu: "isnotgood/nespravedlive-dane.cz" <nespravedlive-dane.cz@noreply.github.com>
> Datum: 23.02.2017 21:49
> Předmět: Re: [isnotgood/nespravedlive-dane.cz] A o kolik
>
> CC: <author@noreply.github.com>
Bohuzel to je asi tema, ktere nepujde vysvetlit na formatu tohoto webu jako "jednohubka". Kazdopadne kdybyste mel nejaky napad, jak to trefne podat - sem s nim :)
