### ISSUE TITLE
Chybí existující progresivní zdanění = solidární daň

### ISSUE THREAD

**Issue by kuba-kubula** [isnotgood/nespravedlive-dane.cz#5]
Jak je popsáno v článku http://www.finance.cz/zpravy/finance/427289-jak-moc-je-v-cesku-progresivni-zdaneni/ - v Česku již lehce "progresivní" zdanění existuje.

U příjmů nad hranici 48násobku rozhodné průměrné mzdy se tento rozdíl daní dalšími 7 %.
http://www.investujeme.cz/solidarni-dan-v-roce-2017/

Tohle by taky bylo fajn "někde" ukázat, a případně přidat do kalkulačky.

Každopádně díky za web.

**Comment by isnotgood** [comment]
Solidarni dan je [zahrnuta tady](https://github.com/isnotgood/nespravedlive-dane.cz/blob/master/svinstvo.js#L149) 

Cokoliv na 118K se dani 22% (15% + 7% navic).

**Comment by zde** [comment]
Jenže těch 7℅ je z hrubé mzdy, nejde to přičíst k 15℅ ze superhrubé.

**Comment by zde** [comment]
Navíc vám tam chybí zastropování odvodů.

**Comment by isnotgood** [comment]
Jasne mate pravdu:) Diky za nalezeni chybky. Tech 7% musi jeste vydelit 1.34 abych to upravil pro superhrubou

Takze:

Hruba: `150 000`
Super hruba: `150 000 x 1.34 = 201 000`
Hranici pro solidarni dan: `112 928`

Dan z prijmu 15%: `201 000 x 0.15 = 30 150`
Solidarni dan z hrubeho: `(150 000 - 112 928) x 0.07 = 2 595`
Hruba: `150 000 - 30 150 - 2 595 = **117 255**`

Dan 15%: `151 323 x 0.15 = 22 698`
Dan 22.2%: `(201 000 - 112 928 * 1.34) x (0.15 + 0.07 / 1.34) = 10 047`
Hruba: `150 000 - 22 698 - 10 047 = **117 255**`

Pocitam spravne?

Strop socialniho (mesicni) je [tady](https://github.com/isnotgood/nespravedlive-dane.cz/blob/master/svinstvo.js#L15)

**Comment by zde** [comment]
Jj, je to správně. Díky, stropu jsem si nevšiml.

Dne 24. 2. 2017 12:21 napsal uživatel "Lukas Weber" <
notifications@github.com>:
